### Use this file to test out your REST call before implementing them in the code

# Local JSON-Server
### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
# @baseUrl = http://192.168.1.6:3000

# Local Firebase Emulator
# @baseUrl = http://192.168.1.6:5001/aidel-backend-firebase-rest/us-central1/api
#@baseUrl = http://localhost:5001/aidel-backend-firebase-rest/us-central1/api

# Live Firebase
@baseUrl = https://us-central1-aidel-backend-firebase-rest.cloudfunctions.net/api

### Request 1 : Get a user whose correct 'login' and 'password'
### Purpose   : To simulate the authentication process.
GET {{baseUrl}}/users?login=danial&password=4444

### Request 2 : Get the counter data  for a given user
##GET {{baseUrl}}/users/user1
GET {{baseUrl}}/subjects/Nna3Efpuw61DO09TGYxa

### Request 3 : Update the information of a given counter
PUT {{baseUrl}}/users/VypSjdQk37gLbZvzctcs
Content-Type: application/json

{
    "password": "try"
}

### Request: Get all users
GET {{baseUrl}}/users

### Request: Add a new user
POST {{baseUrl}}/subjects
Content-Type: application/json

{
    "counter": 0,
    "description": "try",
    "price": 10,
    "title": "try"
}

### Request: Delete a user
DELETE {{baseUrl}}/users/efDrKUbwxAwhWN1tHzrM
